version: 2

models:
  - name: mart_property_core
    description: "Core property entity - Silver Pre-MDM layer. One row per property per source system."
    
  
    tests:
      - dbt_utils.expression_is_true:
          name: property_core_gross_area_gt_zero
          expression: "gross_area > 0"
      - dbt_utils.expression_is_true:
          name: property_core_year_built_range
          expression: "year_built >= 1600 AND year_built <= EXTRACT(YEAR FROM CURRENT_DATE)"
      - dbt_utils.expression_is_true:
          name: property_core_number_of_units_gt_zero
          expression: "number_of_units > 0"
      - dbt_utils.expression_is_true:
          name: floors_only_for_building
          expression: "
            case
              when total_floors is not null
              then ref_property_kind_skey is not null
              else true
            end"
      - dbt_utils.expression_is_true:
          name: floors_only_for_building
          expression: "
            case
              when total_floors is not null
              then ref_property_kind_skey is not null
              else true
            end
          "
 
    columns:
      - name: ref_property_kind_skey
        description: "FK to REF_PROPERTY_KIND"
        tests:
          - not_null
          - relationships:
              to: ref('stg_ref_property_kind')
              field: property_kind_skey

      - name: ref_property_status_skey
        description: "FK to REF_PROPERTY_STATUS"
        tests:
          - relationships:
              to: ref('stg_ref_property_status')
              field: property_status_skey

      - name: parcel_number
        description: "Primary parcel identifier"
        tests:
          - not_null

      - name: gross_area_uom
        description: "Unit of measure for gross area"
        tests:
          - not_null
          - accepted_values:
              values: ['SQFT','SM','ACRES'] 

      - name: property_core_hkey
        description: "MD5 hash key of business attributes"
        tests:
          - not_null
          - unique

      - name: source_unique_id
        description: "Composite identifier SOURCE_SYSTEM|SOURCE_PROPERTY_ID"
        tests:
          - not_null
          - unique